#!/bin/sh
### BEGIN INIT INFO
# Provides:          aesdchar
# Required-Start:    $local_fs 
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: AESD character device driver
### END INIT INFO

case "$1" in
  start)
    echo "Loading aesdchar module"
    /lib/modules/$(uname -r)/extra/aesdchar_load
    ;;
  stop)
    echo "Unloading aesdchar module"
    /lib/modules/$(uname -r)/extra/aesdchar_unload
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
